author: Gerhard
description: (he/him)
markdown: kramdown
title: Te Araroa Southbound
url: https://ta-sobo.gerhardla.nz

plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-sitemap

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false
