title: Te Araroa Southbound · Gerhard
markdown: CommonMark
repository: gerhardlanz/ta-sobo
url: https://ta-sobo.gerhardla.nz
permalink: /:title

plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-titles-from-headings

markdown: CommonMark
commonmark:
  options: ["smart", "unsafe", "hardbreaks"]
  