markdown: CommonMark
permalink: /:title
title: Te Araroa Southbound
url: https://ta-sobo.gerhardla.nz
    
plugins:
  - jekyll-sitemap

markdown: CommonMark
commonmark:
  options: ["smart", "unsafe", "hardbreaks"]
  